### ISSUE TITLE
Reinstall baseboard and panel below kitchen sink

### ISSUE THREAD

**Issue by MetaFight** [OxfordHackspace/HelperWork#14]
There is a carboard panel which conceals the space below the kitchen sink (the space below the counter).

The panel, and its baseboard, were recently removed by someone investigating the ceiling leaks.  They both need to be reinstalled.

**Comment by Ilidur** [comment]
This should be bumped up after they fix the piping.

**Comment by Yanaba** [comment]
Agree. Parts are in cupboard 5 and it looks super lousy to not sort it.

**Comment by Ilidur** [comment]
Covers have been put back.
