### ISSUE TITLE
FAKE: Test task

### ISSUE THREAD

**Issue by paulr4** [OxfordHackspace/HelperWork#4]
Plan moon mission
#1

@uglynewt 
@MetaFight 
@Mellen

**Comment by uglynewt** [comment]
Steps required (now with checkboxes):
- [ ] Poll membership to ascertain popularity of moon.
- [ ] Set up wiki page for sharing rocket designs.
- [x] Doodle poll to schedule the event.
- [ ] Draft press release.

**Comment by MetaFight** [comment]
I don't like the moon.  Actually, I don't even believe our moon exists.  I'd be willing to compromise if we changed the mission target to another planet's moon.  How about Ganymede?

**Comment by NickKolpin** [comment]
@MetaFight destroyed the moon. We no longer need to go there.
