### ISSUE TITLE
OxHack 1.0 Inventory

### ISSUE THREAD

**Issue by NickKolpin** [OxfordHackspace/HelperWork#5]
All the stuff from the OVADA Hackspace location (OxHack 1.0) is being inventoried and put into a closet in the new Hackspace.

**Comment by NickKolpin** [comment]
@MetaFight I can help for about an hour tonight if you share the spreadsheet with me.

**Comment by MetaFight** [comment]
All the pertinent stuff has be successfully inventoried and stored in a single closet.  Thanks to Nick and Matt for the help the other night and to Chris B and Phil B for the help earlier on.  Sorry if I forgot anyone.
