### ISSUE TITLE
Destroy the one ring

### ISSUE THREAD

**Issue by NickKolpin** [OxfordHackspace/HelperWork#8]
We need to destroy something precious:
- [x] Walk into Mordor
- [x] Drop ring into volcano
- [x] Grab a lift home with some eagles
- [x] Find out why the eagles couldn't give you a lift there in the first place.

**Comment by NickKolpin** [comment]
I destroyed the ring, but I'm waiting on the lazy eagles.

**Comment by uglynewt** [comment]
![Problem](https://media.giphy.com/media/m4L2xe2qgTVzq/giphy.gif)

**Comment by NickKolpin** [comment]
I'm back home, job complete!
