### ISSUE TITLE
Create material calibration file for laser cutter

### ISSUE THREAD

**Issue by paulr4** [OxfordHackspace/HelperWork#9]
Create a simple file using the laser cutter software, to allow new materials to be tested with a range of cutting parameters.

It should burn a test pattern including lines at a number of power settings and feed rates, labelled with their cutting parameters. For each new material we buy, a small sample could be cut using the file, as a visual guide to help decide the most appropriate settings for that material.

**Comment by Mellen** [comment]
How is a file created?

**Comment by paulr4** [comment]
On the Lasercut software, on the laser cutter's laptop. I've actually done this task, I'll mark it as closed.
